apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  labels:
    app.kubernetes.io/instance: my-mongodb-sharded
    app.kubernetes.io/name: mongodb-exporter
spec:
  selector:
    app.kubernetes.io/instance: my-mongodb-sharded
    app.kubernetes.io/name: mongodb-exporter
  ports:
    - name: metrics
      port: 9216
      targetPort: 9216