apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: shard0-iowait-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: my-mongodb-sharded-shard0-data
  minReplicaCount: 1
  maxReplicaCount: 3
  pollingInterval: 30       # seconds between checks
  cooldownPeriod: 150       # seconds to wait before scaling down
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-operated.monitoring.svc:9090
        metricName: node_iowait_percent
        query: >
          100 *
          max(
            sum by(instance) (rate(node_cpu_seconds_total{mode="iowait"}[2m]))
            /
            sum by(instance) (rate(node_cpu_seconds_total[2m]))
          )
        threshold: "5"
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          policies:
            - type: Pods
              value: 1
              periodSeconds: 120
          stabilizationWindowSeconds: 150
        scaleDown:
          policies:
            - type: Pods
              value: 1
              periodSeconds: 30
          stabilizationWindowSeconds: 60
