apiVersion: autoscaler.mongodb.io/v1alpha1
kind: MongodAutoscaler
metadata:
  labels:
    app.kubernetes.io/name: mongodboperator
    app.kubernetes.io/managed-by: kustomize
  name: mongodautoscaler-sample
spec:
  # TODO(user): Add fields here
  bitnami:
    releaseName: my-mongodb-sharded
    namespace: default
    servicePort: 27017

  scaleBounds:
    minShards: 1
    maxShards: 2

  policy:
    cpuTargetPercent: 60
    tolerancePercent: 10
    window: 5m
    cooldownSeconds: 300

  prometheus:
    url: http://prometheus-operated.monitoring.svc:9090